/**
 *
 * $Id$
 */
package garden.validation;

import garden.Gardener;
import garden.PathWay;
import garden.Tree;
import garden.Zone;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link garden.Zone}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ZoneValidator {
	boolean validate();

	boolean validateZones(EList<Zone> value);
	boolean validateTrees(EList<Tree> value);
	boolean validatePathways(EList<PathWay> value);
	boolean validateMaintainedBy(EList<Gardener> value);
	boolean validateResponsible(Gardener value);
}
